# Generated by Django 4.2.7 on 2023-11-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciality.speciality', verbose_name='course code')),
            ],
        ),
    ]
